/** POST /appointments helpers (no I/O). */

export function normalizeBeautyproStartTime(time: string): string {
  const t = time.trim();
  if (/^\d{1,2}:\d{2}:\d{2}$/.test(t)) return t;
  if (/^\d{1,2}:\d{2}$/.test(t)) return `${t}:00`;
  return t;
}

/** Body for POST /appointments. Do not send `id` on the appointment or service rows —
 *  ids are generated by BeautyPro. Live API 400s with Unknown parameter 'id'. */
export function buildBeautyproAppointmentCreateBody(input: {
  isoDate: string;
  locationId: string;
  clientId: string;
  comment?: string;
  professional: string;
  start: string;
  services: Array<{ id: string; durationMin: number; masterId?: string; startTime?: string }>;
}): Record<string, unknown> {
  const body: Record<string, unknown> = {
    date: input.isoDate,
    location: input.locationId,
    client: input.clientId,
    state: 'planned',
    services: input.services.map((s, idx) => ({
      service: s.id,
      professional: s.masterId || input.professional,
      start: idx === 0 ? input.start : normalizeBeautyproStartTime(s.startTime ?? input.start),
      duration: s.durationMin || 60,
    })),
  };
  if (input.comment?.trim()) {
    body.comments = input.comment.trim();
  }
  return body;
}
