/** POST /appointments helpers (no I/O). */

export function normalizeBeautyproStartTime(time: string): string {
  const t = time.trim();
  if (/^\d{1,2}:\d{2}:\d{2}$/.test(t)) return t;
  if (/^\d{1,2}:\d{2}$/.test(t)) return `${t}:00`;
  return t;
}

export function addMinutesToBeautyproStart(start: string, minutes: number): string {
  const norm = normalizeBeautyproStartTime(start);
  const m = /^(\d{1,2}):(\d{2})(?::(\d{2}))?$/.exec(norm);
  if (!m) return norm;
  const added = Number.isFinite(minutes) ? minutes : 0;
  let total = Number(m[1]) * 60 + Number(m[2]) + added;
  if (total < 0) total = 0;
  const h = Math.floor(total / 60);
  const min = total % 60;
  const sec = (m[3] ?? '00').padStart(2, '0');
  return `${String(h).padStart(2, '0')}:${String(min).padStart(2, '0')}:${sec}`;
}

export function isBeautyproTimeConflictError(err: unknown): boolean {
  const msg = err instanceof Error ? err.message : String(err);
  return /TIME_CONFLICT|409004/.test(msg);
}

/** Prefer planned/confirmed visit for this client + location + calendar day. */
export function pickSameDayAppointmentId(
  rows: Array<{ id?: string; date?: string | null; location?: string | null; client?: string | null }> | null | undefined,
  opts: { isoDate: string; locationId: string; clientId: string },
): string | null {
  const wanted = opts.isoDate.slice(0, 10);
  for (const row of rows ?? []) {
    if (!row.id) continue;
    const date = String(row.date ?? '').slice(0, 10);
    if (date && date !== wanted) continue;
    if (row.location && row.location !== opts.locationId) continue;
    if (row.client && row.client !== opts.clientId) continue;
    return row.id;
  }
  return null;
}

/** Body for POST /appointments. Do not send `id` on the appointment or service rows —
 *  ids are generated by BeautyPro. Live API 400s with Unknown parameter 'id'.
 *  Same professional: chain starts (12:00 + 115m → 13:55). Parallel overlap → 409 TIME_CONFLICT. */
export function buildBeautyproAppointmentCreateBody(input: {
  isoDate: string;
  locationId: string;
  clientId: string;
  comment?: string;
  professional: string;
  start: string;
  services: Array<{ id: string; durationMin: number; masterId?: string; startTime?: string }>;
}): Record<string, unknown> {
  const firstStart = normalizeBeautyproStartTime(input.start);
  const nextStartByPro = new Map<string, string>();
  const services = input.services.map((s) => {
    const professional = s.masterId || input.professional;
    const duration = s.durationMin || 60;
    const start = nextStartByPro.get(professional) ?? firstStart;
    nextStartByPro.set(professional, addMinutesToBeautyproStart(start, duration));
    return { service: s.id, professional, start, duration };
  });

  const body: Record<string, unknown> = {
    date: input.isoDate,
    location: input.locationId,
    client: input.clientId,
    state: 'planned',
    services,
  };
  if (input.comment?.trim()) {
    body.comments = input.comment.trim();
  }
  return body;
}
