/**
 * follow-up-config.ts
 *
 * Tenant Smart-trigger (remarketing): one silence follow-up after bot message.
 * Stored under Setting key `follow_up_config`. Delay is in hours only.
 * Message text is generated by the sales agent (system prompt + history), not a template.
 */
import { prisma } from './prisma.js';

export interface FollowUpConfig {
  enabled: boolean;
  /** Hours of client silence after last bot outbound before one nudge. */
  delayHours: number;
}

/** Minimum delay: 1 hour. */
export const FOLLOW_UP_DELAY_HOURS_MIN = 1;
/** Maximum delay: 7 days. */
export const FOLLOW_UP_DELAY_HOURS_MAX = 168;
/** Default: 3 days. */
export const FOLLOW_UP_DELAY_HOURS_DEFAULT = 72;

const DEFAULTS: FollowUpConfig = {
  enabled: false,
  delayHours: FOLLOW_UP_DELAY_HOURS_DEFAULT,
};

let _cache: FollowUpConfig | null = null;
let _cacheAt = 0;
const CACHE_TTL_MS = 60_000;

export function clampFollowUpDelayHours(value: unknown): number {
  const n = typeof value === 'number' ? value : Number(value);
  if (!Number.isFinite(n)) return DEFAULTS.delayHours;
  return Math.max(
    FOLLOW_UP_DELAY_HOURS_MIN,
    Math.min(FOLLOW_UP_DELAY_HOURS_MAX, Math.floor(n)),
  );
}

/**
 * Prefer `delayHours`. Legacy `delayMinutes` / `template` are ignored.
 */
export function normalizeFollowUpConfig(
  raw:
    | (Partial<FollowUpConfig> & { delayMinutes?: number; template?: string })
    | null
    | undefined,
): FollowUpConfig {
  const delaySource =
    raw && typeof raw.delayHours === 'number' && Number.isFinite(raw.delayHours)
      ? raw.delayHours
      : DEFAULTS.delayHours;

  return {
    enabled: raw?.enabled === true,
    delayHours: clampFollowUpDelayHours(delaySource),
  };
}

export async function getFollowUpConfig(): Promise<FollowUpConfig> {
  if (_cache && Date.now() - _cacheAt < CACHE_TTL_MS) {
    return _cache;
  }

  const row = await prisma.setting.findUnique({
    where: { key: 'follow_up_config' },
  });

  _cache = normalizeFollowUpConfig(
    (row?.value ?? {}) as Partial<FollowUpConfig> & {
      delayMinutes?: number;
      template?: string;
    },
  );
  _cacheAt = Date.now();
  return _cache;
}

export function invalidateFollowUpConfigCache(): void {
  _cache = null;
  _cacheAt = 0;
}
