#!/usr/bin/env bash
#
# setup-whisper.sh — Idempotent faster-whisper install + model warmup for a tenant.
#
# Called from deploy-client.sh (as the tenant Linux user).
# Safe to re-run: skips steps that are already complete.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${PROJECT_ROOT}"

# Load .env if present (deploy-client already exported vars; this covers manual runs).
if [ -f .env ]; then
  while IFS= read -r _line || [ -n "$_line" ]; do
    [[ "$_line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${_line// }" ]] && continue
    _key="${_line%%=*}"
    _val="${_line#*=}"
    _key="${_key//[[:space:]]/}"
    _val="${_val#\"}" ; _val="${_val%\"}"
    _val="${_val#\'}" ; _val="${_val%\'}"
    export "$_key=$_val"
  done < .env
fi

STT_ENABLED="${STT_ENABLED:-true}"
if [ "${STT_ENABLED}" != "true" ]; then
  echo "  STT_ENABLED=false — skipping faster-whisper setup"
  exit 0
fi

WHISPER_VENV="${PROJECT_ROOT}/.whisper-venv"
WHISPER_CACHE_DIR="${WHISPER_CACHE_DIR:-${PROJECT_ROOT}/.whisper-models}"
WHISPER_MODEL="${WHISPER_MODEL:-small}"
WHISPER_DEVICE="${WHISPER_DEVICE:-cpu}"
WHISPER_COMPUTE_TYPE="${WHISPER_COMPUTE_TYPE:-int8}"
MODEL_MARKER="${WHISPER_CACHE_DIR}/.model-${WHISPER_MODEL}-ready"
REQUIREMENTS="${PROJECT_ROOT}/apps/whisper-server/requirements.txt"

echo "  [whisper] Project: ${PROJECT_ROOT}"
echo "  [whisper] Model: ${WHISPER_MODEL} (${WHISPER_DEVICE}/${WHISPER_COMPUTE_TYPE})"

# ── ffmpeg (required by faster-whisper for m4a/mp3) ──
if command -v ffmpeg >/dev/null 2>&1 && command -v ffprobe >/dev/null 2>&1; then
  echo "  [whisper] ffmpeg/ffprobe: OK"
else
  echo "  [whisper] ffmpeg/ffprobe missing" >&2
  echo "  Run once as root: sudo bash ${SCRIPT_DIR}/install-whisper-system-deps.sh" >&2
  exit 1
fi

# ── Python 3.10+ ──
PYTHON=""
for candidate in python3.12 python3.11 python3.10 python3; do
  if command -v "${candidate}" >/dev/null 2>&1; then
    ver="$("${candidate}" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
    major="${ver%%.*}"
    minor="${ver#*.}"
    if [ "${major}" -ge 3 ] && [ "${minor}" -ge 10 ]; then
      PYTHON="${candidate}"
      break
    fi
  fi
done

if [ -z "${PYTHON}" ]; then
  echo "  ERROR: Python 3.10+ required for faster-whisper" >&2
  echo "  Run as root: sudo bash ${SCRIPT_DIR}/install-whisper-system-deps.sh" >&2
  exit 1
fi
echo "  [whisper] Python: $(${PYTHON} --version)"

# ── venv + pip deps (idempotent) ──
NEED_PIP=0
if [ ! -d "${WHISPER_VENV}" ]; then
  echo "  [whisper] Creating venv at ${WHISPER_VENV}"
  "${PYTHON}" -m venv "${WHISPER_VENV}"
  NEED_PIP=1
elif ! "${WHISPER_VENV}/bin/python" -c "import faster_whisper" 2>/dev/null; then
  NEED_PIP=1
fi

if [ "${NEED_PIP}" -eq 1 ]; then
  echo "  [whisper] Installing Python dependencies..."
  "${WHISPER_VENV}/bin/pip" install --upgrade pip wheel
  "${WHISPER_VENV}/bin/pip" install -r "${REQUIREMENTS}"
else
  echo "  [whisper] venv + faster-whisper: already installed"
fi

# ── Model download / warmup (idempotent marker) ──
mkdir -p "${WHISPER_CACHE_DIR}"
export WHISPER_CACHE_DIR WHISPER_MODEL WHISPER_DEVICE WHISPER_COMPUTE_TYPE
export HF_HOME="${WHISPER_CACHE_DIR}"

if [ -f "${MODEL_MARKER}" ]; then
  echo "  [whisper] Model cache marker present — skipping warmup"
else
  echo "  [whisper] Downloading / warming model (first run may take a few minutes)..."
  "${WHISPER_VENV}/bin/python" "${PROJECT_ROOT}/apps/whisper-server/warmup_model.py"
  touch "${MODEL_MARKER}"
  echo "  [whisper] Model ready — marker ${MODEL_MARKER}"
fi

# ── Service token (generate once if missing in .env) ──
if [ -z "${WHISPER_SERVICE_TOKEN:-}" ]; then
  NEW_TOKEN="$(openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  if [ -f .env ] && grep -q '^WHISPER_SERVICE_TOKEN=' .env; then
    :
  elif [ -f .env ] && [ -n "${NEW_TOKEN}" ]; then
    echo "" >> .env
    echo "# Auto-generated by setup-whisper.sh $(date +%Y-%m-%d)" >> .env
    echo "WHISPER_SERVICE_TOKEN=${NEW_TOKEN}" >> .env
    export WHISPER_SERVICE_TOKEN="${NEW_TOKEN}"
    echo "  [whisper] Appended WHISPER_SERVICE_TOKEN to .env"
  fi
fi

WHISPER_PORT="${WHISPER_SERVICE_PORT:-8100}"
echo "  [whisper] Service will listen on 127.0.0.1:${WHISPER_PORT}"
echo "  [whisper] Setup complete"
