#!/usr/bin/env bash
#
# update-nginx.sh — Regenerate nginx config for an existing client instance
#
# Reads all values from .env (no manual args needed).
# Rewrites /etc/nginx/sites-available/{INSTANCE_ID}-agent.conf,
# tests the config, and reloads nginx.
#
# Run as root from the app directory:
#   sudo bash infra/scripts/update-nginx.sh
#
# Or with explicit .env path:
#   sudo ENV_FILE=/home/blessed/platform-ai-agent-direct/.env bash infra/scripts/update-nginx.sh
#
set -euo pipefail

# ── Load .env ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/../../.env}"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "ERROR: .env not found at ${ENV_FILE}"
  echo "Set ENV_FILE=/path/to/.env or run from the app directory."
  exit 1
fi

# Parse key=value pairs (ignore comments and empty lines)
set -o allexport
# shellcheck disable=SC1090
source <(grep -E '^[A-Z_]+=.+' "${ENV_FILE}" | sed 's/#.*//')
set +o allexport

# ── Validate required vars ──
: "${INSTANCE_ID:?INSTANCE_ID not set in .env}"
: "${API_DOMAIN:?API_DOMAIN not set in .env}"
: "${ADMIN_DOMAIN:?ADMIN_DOMAIN not set in .env}"
: "${API_PORT:?API_PORT not set in .env}"
: "${ADMIN_PORT:?ADMIN_PORT not set in .env}"
CLIENT_NAME="${INSTANCE_NAME:-${INSTANCE_ID}}"
INSTANCE_ID_UPPER="${INSTANCE_ID^^}"

NGINX_CONF="/etc/nginx/sites-available/${INSTANCE_ID}-agent.conf"

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: Run as root (sudo bash $0)"
  exit 1
fi

echo "══════════════════════════════════════════════"
echo "  Update nginx: ${CLIENT_NAME} (${INSTANCE_ID_UPPER})"
echo "  Config file:  ${NGINX_CONF}"
echo "  API:   https://${API_DOMAIN}  → :${API_PORT}"
echo "  Admin: https://${ADMIN_DOMAIN} → :${ADMIN_PORT} (+ /api/ → :${API_PORT})"
echo "══════════════════════════════════════════════"

# Check TLS certs exist
for domain in "${API_DOMAIN}" "${ADMIN_DOMAIN}"; do
  if [[ ! -d "/etc/letsencrypt/live/${domain}" ]]; then
    echo "WARNING: TLS cert not found for ${domain} — using self-signed placeholder."
    echo "         Run certbot to obtain a real cert, then re-run this script."
  fi
done

# ── Backup existing config ──
if [[ -f "${NGINX_CONF}" ]]; then
  BACKUP="${NGINX_CONF}.bak.$(date +%Y%m%d%H%M%S)"
  cp "${NGINX_CONF}" "${BACKUP}"
  echo "Backup: ${BACKUP}"
fi

# ── Write new config ──
cat > "${NGINX_CONF}" <<NGINX
# ${CLIENT_NAME} (${INSTANCE_ID_UPPER}) — generated by update-nginx.sh $(date '+%Y-%m-%d %H:%M:%S')

# ── Admin SPA ──
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${ADMIN_DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${ADMIN_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${ADMIN_DOMAIN}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    # API proxy — /api/* → backend (strips /api prefix)
    location /api/ {
        proxy_pass http://127.0.0.1:${API_PORT}/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Admin SPA static files
    location / {
        proxy_pass http://127.0.0.1:${ADMIN_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}

# ── Backend API + IG webhook ──
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${API_DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${API_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${API_DOMAIN}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    client_max_body_size 10m;

    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
        proxy_pass http://127.0.0.1:${API_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

# ── HTTP → HTTPS redirect ──
server {
    listen 80;
    listen [::]:80;
    server_name ${API_DOMAIN} ${ADMIN_DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}
NGINX

echo "Config written: ${NGINX_CONF}"

# ── Ensure symlink ──
if [[ ! -L "/etc/nginx/sites-enabled/${INSTANCE_ID}-agent.conf" ]]; then
  ln -sf "${NGINX_CONF}" "/etc/nginx/sites-enabled/${INSTANCE_ID}-agent.conf"
  echo "Symlink created: sites-enabled/${INSTANCE_ID}-agent.conf"
fi

# ── Test + reload ──
echo "Testing nginx config..."
nginx -t

echo "Reloading nginx..."
systemctl reload nginx

echo ""
echo "✓ nginx updated and reloaded for ${CLIENT_NAME}"
echo "  Admin: https://${ADMIN_DOMAIN}"
echo "  API:   https://${API_DOMAIN}"
